### ISSUE TITLE
No such file or directory: './l16_ptk710_f8_res224.pth'

### ISSUE THREAD

**Issue by CIMASA** [zhangguiwei610/CAMEL#2]
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/root/autodl-tmp/CAMEL-main/train_camel.py", line 471, in <module>
    main(**OmegaConf.load(args.config))
  File "/root/autodl-tmp/CAMEL-main/train_camel.py", line 175, in main
    eval_config,test_name2loaders,model_without_ddp,tokenizer_umt,device_umt=eval_after_training(umt_config)
  File "/root/autodl-tmp/CAMEL-main/tasks/retrieval.py", line 249, in eval_after_training
    ) = setup_model(
  File "/root/autodl-tmp/CAMEL-main/tasks/shared_utils.py", line 51, in setup_model
    model = model_cls(config=config, tokenizer=tokenizer, is_pretrain=pretrain)
  File "/root/autodl-tmp/CAMEL-main/models/umt.py", line 33, in __init__
    self.vision_encoder = self.build_vision_encoder()
  File "/root/autodl-tmp/CAMEL-main/models/umt.py", line 239, in build_vision_encoder
    vision_encoder = build_vit(self.config.model)
  File "/root/autodl-tmp/CAMEL-main/models/backbones/vit/vit.py", line 443, in build_vit
    state_dict = torch.load(config.vision_encoder.pretrained, map_location='cpu')
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './l16_ptk710_f8_res224.pth'

Your repo doesn‘t offer this model, and I try to find it in https://github.com/OpenGVLab/[unmasked_teacher](https://github.com/OpenGVLab/unmasked_teacher), but their MODEL_ZOO  doesn't work any more, so could u please update this model to ur repo.

**Comment by InHwanJin** [comment]
same issue

**Comment by junhaoooxia** [comment]
it could be found here [https://huggingface.co/OpenGVLab/UMT/tree/main](url)
